# Generated by Django 5.1.2 on 2024-10-27 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='The text prompt used to generate the image.', verbose_name='Prompt')),
                ('image_file', models.ImageField(blank=True, help_text='The generated image file.', null=True, upload_to='generated_images/', verbose_name='Image File')),
                ('image_url', models.URLField(blank=True, help_text='The URL of the generated image.', max_length=500, null=True, verbose_name='Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the image was generated.', verbose_name='Created At')),
                ('model_used', models.CharField(choices=[('dall-e-2', 'DALL-E 2'), ('dall-e-3', 'DALL-E 3')], default='dall-e-2', help_text='The AI model used to generate the image.', max_length=20, verbose_name='Model Used')),
                ('n', models.PositiveSmallIntegerField(default=1, help_text='The number of images generated.', verbose_name='Number of Images')),
                ('quality', models.CharField(blank=True, choices=[('standard', 'Standard'), ('hd', 'HD')], help_text="The quality setting used during generation. Only supported for 'dall-e-3'.", max_length=20, null=True, verbose_name='Quality')),
                ('response_format', models.CharField(choices=[('url', 'URL'), ('b64_json', 'Base64 JSON')], default='url', help_text="The response format (e.g., 'url', 'b64_json').", max_length=20, verbose_name='Response Format')),
                ('size', models.CharField(default='1024x1024', help_text='The size of the generated image.', max_length=20, verbose_name='Image Size')),
                ('style', models.CharField(blank=True, choices=[('vivid', 'Vivid'), ('natural', 'Natural')], help_text="The style setting used during generation. Only supported for 'dall-e-3'.", max_length=20, null=True, verbose_name='Style')),
                ('revised_prompt', models.TextField(blank=True, help_text='The revised prompt used by the AI model, if any.', null=True, verbose_name='Revised Prompt')),
                ('is_shared', models.BooleanField(default=False, help_text='Indicates whether the image is shared publicly.', verbose_name='Is Shared')),
                ('shared_at', models.DateTimeField(blank=True, help_text='The date and time when the image was shared.', null=True, verbose_name='Shared At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='The date and time when the shared image expires.', null=True, verbose_name='Expires At')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for sharing the image.', unique=True, verbose_name='Share Token')),
                ('user', models.ForeignKey(help_text='The user who generated this image.', on_delete=django.db.models.deletion.CASCADE, related_name='image_generations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Image Generation',
                'verbose_name_plural': 'Image Generations',
                'ordering': ['-created_at'],
            },
        ),
    ]
