# Generated by Django 5.1.2 on 2024-11-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegeneration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the image was generated.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='imagegeneration',
            name='response_format',
            field=models.CharField(choices=[('url', 'URL'), ('b64_json', 'Base64 JSON')], db_index=True, default='url', help_text="The response format (e.g., 'url', 'b64_json').", max_length=20, verbose_name='Response Format'),
        ),
    ]
