# Generated by Django 5.1.2 on 2024-11-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorstore',
            name='expires_at',
            field=models.IntegerField(default=1, help_text='The Unix timestamp (in seconds) for when the vector store will expire.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vectorstore',
            name='last_active_at',
            field=models.IntegerField(default=1, help_text='The Unix timestamp (in seconds) for when the vector store was last active.'),
            preserve_default=False,
        ),
    ]
