# Generated by Django 5.1.2 on 2024-12-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image_file',
            field=models.ImageField(blank=True, help_text='The image associated with the file.', null=True, upload_to='generated_images/', verbose_name='Image File'),
        ),
        migrations.AddField(
            model_name='file',
            name='image_url',
            field=models.URLField(blank=True, help_text='The URL of the image associated with the file.', max_length=500, null=True, verbose_name='Image URL'),
        ),
    ]
