# Generated by Django 5.1.2 on 2024-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_file_image_file_file_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image_file',
            field=models.ImageField(blank=True, help_text='The image associated with the file.', null=True, upload_to='file_images/', verbose_name='Image File'),
        ),
    ]
