# Generated by Django 5.1.2 on 2024-10-13 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A summary of the conversation.', max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the conversation was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the conversation was last updated.', verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='The user who owns this conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], help_text='Indicates whether the sender is the user or the AI.', max_length=5, verbose_name='Sender')),
                ('message_body', models.TextField(help_text='The content of the message.', verbose_name='Message Body')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time when the message was created.', verbose_name='Timestamp')),
                ('conversation', models.ForeignKey(help_text='The conversation to which this message belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
