# Generated by Django 5.1.2 on 2025-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='admin_key',
            field=models.CharField(blank=True, default='', help_text='Admin-level API key for analytics', max_length=255),
        ),
    ]
